Update build-ami.yml

diff --git a/.github/workflows/build-ami.yml b/.github/workflows/build-ami.yml
--- a/.github/workflows/build-ami.yml
+++ b/.github/workflows/build-ami.yml
@@ -70,6 +70,36 @@ jobs:
 #try
     - name: Build AMI
       env:
+        AWS_REGION : ${{ secrets.AWS_REGION }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
       run: packer build ami.us-east-1.pkr.hcl
+
+    - name: Create new Launch Template version
+      run: |
+        latest_ami=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
+        aws ec2 create-launch-template-version --launch-template-id ${{ secrets.LAUNCH_TEMPLATE_ID }} --source-version '$Latest' --launch-template-data "ImageId=$latest_ami"
+
+    - name: Update ASG to use latest Launch Template version 
+      run: |
+        aws autoscaling update-auto-scaling-group --auto-scaling-group-name ${{ secrets.ASG_NAME }} --launch-template LaunchTemplateId=${{ secrets.LAUNCH_TEMPLATE_ID }},Version='$Latest'
+      
+    - name: Start ASG instance refresh
+      run: |
+        instance_refresh_id=$(aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ secrets.ASG_NAME }} --query 'InstanceRefreshId' --output text)
+
+    - name: Wait for instance refresh to complete
+      run: |
+        status="IN_PROGRESS"
+        while [ "$status" == "IN_PROGRESS" ]; do
+          status=$(aws autoscaling describe-instance-refreshes --instance-refresh-ids $instance_refresh_id --query 'InstanceRefreshes[].Status' --output text)
+          sleep 15
+        done
+          
+    - name: Check final instance refresh status  
+      run: |
+        final_status=$(aws autoscaling describe-instance-refreshes --instance-refresh-ids $instance_refresh_id --query 'InstanceRefreshes[].Status' --output text)
+        if [ "$final_status" != "Successful" ]; then
+          echo "Instance refresh failed with status $final_status"
+          exit 1
+        fi
